---
title: "ADMIXTURE"
author: "Stella Bähr"
date: "2025-01-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load the libraries and colors etc
```{r, echo = FALSE}
setwd("/g/huber/users/baehr/admixture")
library(tidyverse)
library(ggplot2)
options(bitmapType='cairo')

c("#000000", "#E69F00","#56B4E9","#009E73","#F0E442","#0072B2","#D55E00","#CC79A7")
```

##EHT BF Only Analysis
###CV Error

```{r}
CVs <- read.table("ehtbf/ehtbf_CV.csv", sep = " ")
CVs <- CVs[, 3:4] ## drop the first two columns
## Remove the formatting around the K values:
CVs[, 1] <- gsub(x = CVs[, 1], pattern = "\\(K=",
                replacement = "")
CVs[, 1] <- gsub(x = CVs[, 1], pattern = "\\):",
                replacement = "") 
CVs$V3 <- as.integer(CVs$V3)

plot(CVs, xlab = "K", ylab = "CV error")

CVerror <- ggplot(data=CVs, aes(x=V3, y=V4)) +
  geom_point()+
  geom_line(linetype = "dashed")+
  ylab("cross-validation error")+
  xlab("K")+
  theme_classic()

ggsave("../plots/admixture_ehtbf_CV.pdf", plot = CVerror, height = 3, width = 5)

```


### Data Manipulation

```{r}

#import most promising admixture output
ad2 <- read.table("ehtbf/ehtbf_admixture.2.Q")

#get the .fam file so we have sample names from which to extract meta data
#samps<-read.table("ehtbf/ehtbf_admixture.fam")[,2]
samps <- sample_names$V1

ad2 <- cbind(samps, ad2)
ad2$samps <- sub("(.*?_72).*", "\\1", ad2$samps)

# sort out the individual metadata
# bednet
net<- rep(NA, length(ad2$samps))
net[grep("IG2", ad2$samps)] <- "IG2"
net[grep("PND", ad2$samps)] <- "PermaNet_Dual"
# location
loc <- rep(NA, length(ad2$samps))
loc[grep("Tie", ad2$samps)] <- "Tiefora"
loc[grep("Ten", ad2$samps)] <- "Tengrela"
#mortality
mort <- rep(NA, length(ad2$samps))
mort[grep("prior_72", ad2$samps)] <- "Within 72h"
mort[grep("after_72", ad2$samps)] <- "After 72h"

ad2meta <- as_tibble(data.frame(ad2, loc, net, mort))

#change to long format, change cols to pivot depending on how many there are
ad2meta_long <- ad2meta %>%
  pivot_longer(
    cols = c(V1, V2),             
    names_to = "pop",       
    values_to = "proportion"
  )


```

### Plot

```{r}

k2plot <- ggplot(ad2meta_long, aes(factor(samps), proportion, fill = factor(pop)))+
  geom_col(color = "gray", size = 0.1) +
  scale_fill_manual(values = c("#332288","#44AA99"))+
  facet_grid(~fct_inorder(loc), switch = "x", scales = "free", space = "free") +
  theme_minimal() + labs(x = "Individuals", title = "K=2", y = "Ancestry") +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_discrete(expand = expand_scale(add = 1)) +
  theme(
    panel.spacing.x = unit(0.1, "lines"),
    axis.text.x = element_blank(),
    panel.grid = element_blank()
  )+
  guides(fill="none")

k2plot

ggsave("../plots/admixture_ehtbf_k2.pdf", plot = k2plot, height = 3, width = 5)
```
##With Ag1000G samples

###CV Error

```{r}
CVs <- read.table("3L_merged/3L_merged_admixture_CV.csv", sep = " ")
CVs <- CVs[, 3:4] ## drop the first two columns
## Remove the formatting around the K values:
CVs[, 1] <- gsub(x = CVs[, 1], pattern = "\\(K=",
                replacement = "")
CVs[, 1] <- gsub(x = CVs[, 1], pattern = "\\):",
                replacement = "") 

plot(CVs, xlab = "K", ylab = "CV error")

ggplot(data=CVs, aes(x=V3, y=V4, group =1)) +
  geom_point()+
  geom_line(linetype = "dashed")+
  ylab("cross-validation error")+
  xlab("K")+
  theme_classic()

```



### Data Manipulation

```{r}

#import most promising admixture output
mergedad2 <- read.table("3L_merged/3L_merged_admixture.2.Q")
mergedad3 <- read.table("3L_merged/3L_merged_admixture.3.Q")

#get the .fam file so we have sample names from which to extract meta data
samplesmerged <- read.table("3L_merged/3L_merged_admixture.fam")[,2]

admixmeta <- cbind(samplesmerged, mergedad2)

admixmeta$dataset <- ifelse(grepl("^A", admixmeta$samplesmerged), "Ag1000G BF",
                  ifelse(grepl("^R", admixmeta$samplesmerged), "EHT BF", NA))

admixmeta <- admixmeta[, !(names(admixmeta) %in% c("V1", "V2"))]

#edit the sample name (needs to be more sophisticated for the eht bf samples)
admixmeta$samplesmerged <- sapply(admixmeta$samplesmerged, function(x) {
  if (startsWith(x, "A")) {
    # Split by "_" and keep the first substring
    strsplit(x, "_")[[1]][1]
  } else if (startsWith(x, "R")) {
    # Split by "_" and keep the first 5 substrings
    paste(head(strsplit(x, "_")[[1]], 5), collapse = "_")
  } else {
    # Default case: return the original value
    x
  }
})


#Add relevant metadata for plotting
metadata_BF <- read_csv("../ag1000g/metadata_BF.csv")

admixmeta <- admixmeta %>%
  left_join(metadata_BF %>% select(sample_id, aim_species), 
            by = c("samplesmerged" = "sample_id")) %>%
  mutate(species = ifelse(is.na(aim_species), "unknown", aim_species)) %>%
  select(-aim_species)

source <- rep(NA, length(admixmeta$samplesmerged))
source <- ifelse(grepl("Tie", admixmeta$samplesmerged), "Tiefora",
         ifelse(grepl("Ten", admixmeta$samplesmerged), "Tengrela",
         ifelse(grepl("arabiensis", admixmeta$species), "Ag1000G An. arabiensis",
         ifelse(grepl("coluzzii", admixmeta$species), "Ag1000G An. coluzzii",
         ifelse(grepl("gambiae", admixmeta$species), "Ag1000G An. gambiae", NA)))))

mortality <- rep(NA, length(admixmeta$samplesmerged))
mortality <- ifelse(grepl("within_72h", admixmeta$samplesmerged), "Within 72h",
            ifelse(grepl("after_72", admixmeta$samplesmerged), "After 72h",
            ifelse(grepl("Ag1000G BF", admixmeta$dataset), "Ag1000G NA", NA)))

#now lets put together with the original values from admixture

k2mergedmeta <- as_tibble(cbind(admixmeta, Source, Mortality, mergedad2[, c("V1", "V2")]))
k3mergedmeta <- as_tibble(cbind(admixmeta, Source, Mortality, mergedad3[, c("V1", "V2","V3")]))

#change to long format, change cols to pivot depending on how many there are
k2mergedmeta_long <- k2mergedmeta %>%
  pivot_longer(
    cols = c(V1, V2),             
    names_to = "pop",       
    values_to = "proportion"
  )

k3mergedmeta_long <- k3mergedmeta %>%
  pivot_longer(
    cols = c(V1, V2, V3),             
    names_to = "pop",       
    values_to = "proportion"
  )

```

### Plot

```{r}

k2mergedplot <- ggplot(testnoara, aes(factor(samplesmerged), proportion, fill = factor(pop)))+
  geom_col(color = "gray", size = 0.1) +
  scale_fill_manual(values = c("#332288","#44AA99"))+
  facet_grid(~fct_inorder(Source), switch = "x", scales = "free", space = "free") +
  theme_minimal() + labs(x = "Individuals", title = "K=2", y = "Ancestry") +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_discrete(expand = expand_scale(add = 1)) +
  theme(
    panel.spacing.x = unit(0.1, "lines"),
    axis.text.x = element_blank(),
    panel.grid = element_blank()
  )+
  guides(fill="none")

k2mergedplot

ggsave("../plots/admixture_merged_k2_noara.pdf", plot = k2mergedplot, height = 3, width = 7)

k3mergedplot <- ggplot(k3mergedmeta_long, aes(factor(samplesmerged), proportion, fill = factor(pop)))+
  geom_col(color = "gray", size = 0.1) +
  scale_fill_manual(values = c("#882255","#332288","#44AA99","black","red"))+
  facet_grid(~fct_inorder(Source), switch = "x", scales = "free", space = "free") +
  theme_minimal() + labs(x = "Individuals", title = "K=3", y = "Ancestry") +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_discrete(expand = expand_scale(add = 1)) +
  theme(
    panel.spacing.x = unit(0.1, "lines"),
    axis.text.x = element_blank(),
    panel.grid = element_blank()
  )+
  guides(fill="none")

k3mergedplot
ggsave("../plots/admixture_merged_k3.pdf", plot = k3mergedplot, height = 3, width = 10)

```

## With Ag1000G, AT, Goundry and Tengrela samples

###CV Error

```{r}
CVs <- read.table("everything_tengrela/cv_errors.txt", sep = " ")
CVs <- CVs[, 3:4] ## drop the first two columns
## Remove the formatting around the K values:
CVs[, 1] <- gsub(x = CVs[, 1], pattern = "\\(K=",
                replacement = "")
CVs[, 1] <- gsub(x = CVs[, 1], pattern = "\\):",
                replacement = "") 
CVs$V3 <- as.integer(CVs$V3)

plot(CVs, xlab = "K", ylab = "CV error")
#plot(CVs, xlab = "K", ylab = "CV error")

pCVeverything <- ggplot(data=CVs, aes(x=V3, y=V4, group =1)) +
  geom_point()+
  geom_line(linetype = "dashed")+
  ylab("cross-validation error")+
  xlab("K")+
  theme_classic()+
  scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12))

pCVeverything

ggsave("../plots/ehtbf_final/admixture/admixture_everything_CV.pdf", plot = pCVeverything,
       height =3, width = 5 ) 

```

###Data Manipulation
```{r}
#import most promising admixture outputs
everythingad3 <- read.table("old_everything_tengrela/old_everything_tengrela_admixture_final_3L.3.Q")
everythingad4 <- read.table("everything_tengrela/everything_tengrela_admixture_final.4.Q")
everythingad5 <- read.table("old_everything_tengrela/old_everything_tengrela_admixture_final_3L.5.Q")
everythingad6 <- read.table("old_everything_tengrela/old_everything_tengrela_admixture_final_3L.6.Q")
everythingad7 <- read.table("old_everything_tengrela/old_everything_tengrela_admixture_final.7.Q")


#get the .fam file so we have sample names from which to extract meta data
samples <- read.table("everything_tengrela/everything_tengrela_admixture_final.fam")[,2]

#from here on out, only focus on one 
admixmeta <- cbind(samples, everythingad4)

admixmeta$dataset <- ifelse(grepl("^AB", admixmeta$sample), "Ag1000G BF",
                  ifelse(grepl("^R", admixmeta$sample), "This Study",
                  ifelse(grepl("^ATG1", admixmeta$sample), "AT",  
                  ifelse(grepl("^ATG2|^ATG3", admixmeta$sample), "Goundry",
                  ifelse(grepl("Tengrela", admixmeta$sample), "Tengrela (2019)",  
                  NA)))))



#Add relevant metadata for plotting
metadata_BF <- read_csv("../ag1000g/metadata_BF.csv")
metadata_EHTBF <- read_tsv("../stuff/samplesets/samples_all_species.txt", col_names = c("sample", "manual_species"))



admixmeta <- admixmeta %>%
  left_join(metadata_BF %>% select(sample_id, aim_species), 
            by = c("samples" = "sample_id")) %>%
  # Join with manual_species where aim_species is NA
  left_join(metadata_EHTBF, by = c("samples" = "sample")) %>%
  mutate(species = case_when(
    !is.na(aim_species) ~ aim_species,
    !is.na(manual_species) ~ manual_species,
    TRUE ~ "unknown"
  )) %>%
  select(-aim_species, -manual_species)

admixmeta <- admixmeta %>%
  mutate(source = case_when(
    str_detect(samples, "Tie|Ten_") & str_detect(species, "gambiae") ~ "An. gamb. (This Study)",
    str_detect(samples, "Tie|Ten_") & str_detect(species, "coluzzii") ~ "An. col. (This Study)",
    str_detect(samples, "Tie|Ten_") & str_detect(species, "arabiensis") ~ "An. ara. (This Study)",
    
    str_detect(species, "gambiae") ~ "An. gamb. (Ag1000G)",
    str_detect(species, "coluzzii") ~ "An. col. (Ag1000G)",
    str_detect(species, "arabiensis") ~ "An. ara (Ag1000G)",
    
    str_detect(samples, "^ATG1") ~ "AT",
    str_detect(samples, "^ATG2|^ATG3") ~ "Goundry",
    str_detect(samples, "Tengrela") ~ "Tengrela (2019)",
    
    TRUE ~ NA_character_
  ))


#now lets put together with the original values from admixture

#admixmeta <- as_tibble(cbind(admixmeta, source))

#change to long format, change cols to pivot depending on how many there are

k4_everything_long <- admixmeta %>%
  pivot_longer(
    cols = c(V1, V2, V3,V4),             
    names_to = "pop",       
    values_to = "proportion"
  )
```

###Plot

```{r}
peverythingk4 <- ggplot(k4_everything_long, aes(factor(samples), proportion, fill = factor(pop)))+
  geom_col(color = "gray", size = 0.01) +
  scale_fill_manual(values = c("#000000", "#E69F00","#56B4E9","#009E73","#F0E442","#CC79A7"))+
  facet_grid(~fct_inorder(source), switch = "x", scales = "free", space = "free") +
  theme_minimal() + labs(x = element_blank(), title = "K=4", y = "Ancestry") +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_discrete(expand = expand_scale(add = 3)) +
  theme(
    panel.spacing.x = unit(0.1, "lines"),
    axis.text.x = element_blank(),
    panel.grid = element_blank(),
    strip.text.x.bottom = element_text(angle = 90, hjust = 1, size = 8)
  )+
  guides(fill="none")

peverythingk4



ggsave("../plots/ehtbf_coluzzii/thesis/admixture_k4.pdf", plot = peverythingk4, height = 6, width = 18, units = "cm")
```


